version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --db=postgres --db-url-host=postgres --db-username=keycloak --db-password=keycloak --db-url-database=keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
